# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chit}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Robin Lu"]
  s.date = %q{2010-12-18}
  s.default_executable = %q{chit}
  s.description = %q{A command line cheat sheet utility based on git}
  s.email = %q{iamawalrus@gmail.com}
  s.executables = ["chit"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "bin/chit",
     "chit.gemspec",
     "lib/chit.rb",
     "lib/wrap.rb",
     "resources/chitrc",
     "test/test_chit.rb",
     "tools/chit-bash-completion.sh",
     "tools/chit.tmCommand"
  ]
  s.homepage = %q{http://github.com/robin/chit}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A command line cheat sheet utility based on git}
  s.test_files = [
    "test/test_chit.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

